FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev
WORKDIR /app/src
COPY . .
RUN dotnet restore "./simple-budget.bff.csproj"
RUN dotnet build "./simple-budget.bff.csproj"

RUN chmod 755 ./entrypoint.sh
ENTRYPOINT [ "sh", "-c", "./entrypoint.sh" ]