FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev
RUN dotnet nuget add source /app/packages -n local
WORKDIR /app/src
COPY ./entrypoint.sh ./

RUN chmod 755 ./entrypoint.sh
ENTRYPOINT [ "sh", "-c", "./entrypoint.sh" ]